import os

Import('lib_env')

sources = [
    'AbstractStateBlock.cpp',
    'CurrentStateBlock.cpp',
    'LinuxSchedStateBlock.cpp',
]

libs = ['delorean']

lib_env.Append(LIBS=libs)

Return(['sources'])
