import os

Import('lib_env')

sources = [
    'ChromeGraphBuilderBlock.cpp',
    'GraphBuilderBlock.cpp',
    'LinuxPerfBuilderBlock.cpp',
    'LinuxStatusBuilderBlock.cpp',
    'LinuxSyscallBuilderBlock.cpp',
]

Return(['sources'])
