import os

Import('lib_env')

sources = [
    'AbstractRpcMessage.cpp',
    'AbstractRpcRequest.cpp',
    'AbstractRpcResponse.cpp',
    'AbstractRpcNotification.cpp',
    'AbstractJsonRpcMessageEncoder.cpp',
    'AbstractJsonRpcMessageDecoder.cpp',
]

lib_env.ParseConfig('pkg-config --cflags --libs yajl')

Return(['sources'])
