/* Copyright (c) 2014 Francois Doray <francois.pierre-doray@polymtl.ca>
 *
 * This file is part of tigerbeetle.
 *
 * tigerbeetle is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * tigerbeetle is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with tigerbeetle.  If not, see <http://www.gnu.org/licenses/>.
 */
#include "gtest/gtest.h"
#include "trace/TraceSet.hpp"
#include "trace/TraceSetIterator.hpp"
#include "value/Utils.hpp"

namespace tibee {
namespace trace {

namespace {

const char* kExpectedEvents[] = {
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296688683178\n"
    "    fields = {\n"
    "        baddr = 140734025371648\n"
    "        sopath = \"[vdso]\"\n"
    "        size = 0\n"
    "        mtime = -1\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690190547\n"
    "    fields = {\n"
    "        baddr = 140536533020672\n"
    "        sopath = \"/home/fdoray/src/lttng/lttng-ust/doc/examples/demo/lttng-ust-provider-ust-tests-demo.so\"\n"
    "        size = 64555\n"
    "        mtime = 1411484586\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690209274\n"
    "    fields = {\n"
    "        baddr = 140536530911232\n"
    "        sopath = \"/home/fdoray/src/lttng/lttng-ust/doc/examples/demo/lttng-ust-provider-ust-tests-demo3.so\"\n"
    "        size = 29856\n"
    "        mtime = 1411484586\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690227721\n"
    "    fields = {\n"
    "        baddr = 140536528797696\n"
    "        sopath = \"/lib/x86_64-linux-gnu/libdl-2.19.so\"\n"
    "        size = 14664\n"
    "        mtime = 1409205721\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690240019\n"
    "    fields = {\n"
    "        baddr = 140536524840960\n"
    "        sopath = \"/lib/x86_64-linux-gnu/libc-2.19.so\"\n"
    "        size = 1845024\n"
    "        mtime = 1409205721\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo:starting\"\n"
    "    ts = 1411853296690252877\n"
    "    fields = {\n"
    "        value = 123\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690257349\n"
    "    fields = {\n"
    "        baddr = 140536522412032\n"
    "        sopath = \"/home/fdoray/src/lttng/lttng-ust/liblttng-ust/.libs/liblttng-ust.so.0.0.0\"\n"
    "        size = 1720002\n"
    "        mtime = 1411484579\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853296690265454\n"
    "    fields = {\n"
    "        intfield = 0\n"
    "        intfield2 = 0\n"
    "        longfield = 0\n"
    "        netintfield = 0\n"
    "        netintfieldhex = 0\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690269367\n"
    "    fields = {\n"
    "        baddr = 140536535138304\n"
    "        sopath = \"/lib/x86_64-linux-gnu/ld-2.19.so\"\n"
    "        size = 149120\n"
    "        mtime = 1409205721\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853296690273001\n"
    "    fields = {\n"
    "        intfield = 1\n"
    "        intfield2 = 1\n"
    "        longfield = 1\n"
    "        netintfield = 1\n"
    "        netintfieldhex = 1\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853296690279709\n"
    "    fields = {\n"
    "        intfield = 2\n"
    "        intfield2 = 2\n"
    "        longfield = 2\n"
    "        netintfield = 2\n"
    "        netintfieldhex = 2\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690284461\n"
    "    fields = {\n"
    "        baddr = 140536520208384\n"
    "        sopath = \"/home/fdoray/src/lttng/lttng-ust/liblttng-ust/.libs/liblttng-ust-tracepoint.so.0.0.0\"\n"
    "        size = 144429\n"
    "        mtime = 1411484568\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853296690286417\n"
    "    fields = {\n"
    "        intfield = 3\n"
    "        intfield2 = 3\n"
    "        longfield = 3\n"
    "        netintfield = 3\n"
    "        netintfieldhex = 3\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853296690293125\n"
    "    fields = {\n"
    "        intfield = 4\n"
    "        intfield2 = 4\n"
    "        longfield = 4\n"
    "        netintfield = 4\n"
    "        netintfieldhex = 4\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690296200\n"
    "    fields = {\n"
    "        baddr = 140536518078464\n"
    "        sopath = \"/lib/x86_64-linux-gnu/librt-2.19.so\"\n"
    "        size = 31792\n"
    "        mtime = 1409205721\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo:done\"\n"
    "    ts = 1411853296690300392\n"
    "    fields = {\n"
    "        value = 456\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo3:done\"\n"
    "    ts = 1411853296690307101\n"
    "    fields = {\n"
    "        value = 42\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690309616\n"
    "    fields = {\n"
    "        baddr = 140536515952640\n"
    "        sopath = \"/usr/local/lib/liburcu-bp.so.3.0.0\"\n"
    "        size = 107612\n"
    "        mtime = 1411484502\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690321355\n"
    "    fields = {\n"
    "        baddr = 140536513822720\n"
    "        sopath = \"/usr/local/lib/liburcu-cds.so.3.0.0\"\n"
    "        size = 146138\n"
    "        mtime = 1411484502\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853296690333095\n"
    "    fields = {\n"
    "        baddr = 140536511602688\n"
    "        sopath = \"/lib/x86_64-linux-gnu/libpthread-2.19.so\"\n"
    "        size = 141574\n"
    "        mtime = 1409205726\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469186692760\n"
    "    fields = {\n"
    "        baddr = 140735869771776\n"
    "        sopath = \"[vdso]\"\n"
    "        size = 0\n"
    "        mtime = -1\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469186756208\n"
    "    fields = {\n"
    "        baddr = 139758368968704\n"
    "        sopath = \"/home/fdoray/src/lttng/lttng-ust/doc/examples/demo/lttng-ust-provider-ust-tests-demo.so\"\n"
    "        size = 64555\n"
    "        mtime = 1411484586\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196598410\n"
    "    fields = {\n"
    "        baddr = 139758366859264\n"
    "        sopath = \"/home/fdoray/src/lttng/lttng-ust/doc/examples/demo/lttng-ust-provider-ust-tests-demo3.so\"\n"
    "        size = 29856\n"
    "        mtime = 1411484586\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196657386\n"
    "    fields = {\n"
    "        baddr = 139758364745728\n"
    "        sopath = \"/lib/x86_64-linux-gnu/libdl-2.19.so\"\n"
    "        size = 14664\n"
    "        mtime = 1409205721\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196677231\n"
    "    fields = {\n"
    "        baddr = 139758360788992\n"
    "        sopath = \"/lib/x86_64-linux-gnu/libc-2.19.so\"\n"
    "        size = 1845024\n"
    "        mtime = 1409205721\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196707697\n"
    "    fields = {\n"
    "        baddr = 139758358360064\n"
    "        sopath = \"/home/fdoray/src/lttng/lttng-ust/liblttng-ust/.libs/liblttng-ust.so.0.0.0\"\n"
    "        size = 1720002\n"
    "        mtime = 1411484579\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196742076\n"
    "    fields = {\n"
    "        baddr = 139758371086336\n"
    "        sopath = \"/lib/x86_64-linux-gnu/ld-2.19.so\"\n"
    "        size = 149120\n"
    "        mtime = 1409205721\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196766672\n"
    "    fields = {\n"
    "        baddr = 139758356156416\n"
    "        sopath = \"/home/fdoray/src/lttng/lttng-ust/liblttng-ust/.libs/liblttng-ust-tracepoint.so.0.0.0\"\n"
    "        size = 144429\n"
    "        mtime = 1411484568\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo:starting\"\n"
    "    ts = 1411853469196778691\n"
    "    fields = {\n"
    "        value = 123\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196783163\n"
    "    fields = {\n"
    "        baddr = 139758354026496\n"
    "        sopath = \"/lib/x86_64-linux-gnu/librt-2.19.so\"\n"
    "        size = 31792\n"
    "        mtime = 1409205721\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853469196797138\n"
    "    fields = {\n"
    "        intfield = 0\n"
    "        intfield2 = 0\n"
    "        longfield = 0\n"
    "        netintfield = 0\n"
    "        netintfieldhex = 0\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196803008\n"
    "    fields = {\n"
    "        baddr = 139758351900672\n"
    "        sopath = \"/usr/local/lib/liburcu-bp.so.3.0.0\"\n"
    "        size = 107612\n"
    "        mtime = 1411484502\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853469196813350\n"
    "    fields = {\n"
    "        intfield = 1\n"
    "        intfield2 = 1\n"
    "        longfield = 1\n"
    "        netintfield = 1\n"
    "        netintfieldhex = 1\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196819499\n"
    "    fields = {\n"
    "        baddr = 139758349770752\n"
    "        sopath = \"/usr/local/lib/liburcu-cds.so.3.0.0\"\n"
    "        size = 146138\n"
    "        mtime = 1411484502\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853469196829002\n"
    "    fields = {\n"
    "        intfield = 2\n"
    "        intfield2 = 2\n"
    "        longfield = 2\n"
    "        netintfield = 2\n"
    "        netintfieldhex = 2\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196835990\n"
    "    fields = {\n"
    "        baddr = 139758347550720\n"
    "        sopath = \"/lib/x86_64-linux-gnu/libpthread-2.19.so\"\n"
    "        size = 141574\n"
    "        mtime = 1409205726\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853469196845213\n"
    "    fields = {\n"
    "        intfield = 3\n"
    "        intfield2 = 3\n"
    "        longfield = 3\n"
    "        netintfield = 3\n"
    "        netintfieldhex = 3\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo2:loop\"\n"
    "    ts = 1411853469196861704\n"
    "    fields = {\n"
    "        intfield = 4\n"
    "        intfield2 = 4\n"
    "        longfield = 4\n"
    "        netintfield = 4\n"
    "        netintfieldhex = 4\n"
    "        arrfield1 = [\n"
    "            1\n"
    "            2\n"
    "            3\n"
    "        ]\n"
    "        arrfield2 = \"test\"\n"
    "        _seqfield1_length = 4\n"
    "        seqfield1 = [\n"
    "            116\n"
    "            101\n"
    "            115\n"
    "            116\n"
    "        ]\n"
    "        _seqfield2_length = 4\n"
    "        seqfield2 = \"/ Unable to read ctf string sequence. /\"\n"
    "        stringfield = \"test\"\n"
    "        floatfield = 2222\n"
    "        doublefield = 2\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_baddr_statedump:soinfo\"\n"
    "    ts = 1411853469196875679\n"
    "    fields = {\n"
    "        baddr = 4194304\n"
    "        sopath = \"/home/fdoray/src/lttng/lttng-ust/doc/examples/demo/demo\"\n"
    "        size = 24563\n"
    "        mtime = 1411484586\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo:done\"\n"
    "    ts = 1411853469196877636\n"
    "    fields = {\n"
    "        value = 456\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
    "{\n"
    "    name = \"ust_tests_demo3:done\"\n"
    "    ts = 1411853469196893568\n"
    "    fields = {\n"
    "        value = 42\n"
    "    }\n"
    "    context = {\n"
    "    }\n"
    "}",
};

const size_t kExpectedNumEvents = sizeof(kExpectedEvents) / sizeof(char*);

}  // namespace

TEST(TraceSetIterator, TraceIteration)
{
    TraceSet traceSet;
    EXPECT_TRUE(traceSet.addTrace("test_data/ust_a/ust/uid/1000/64-bit"));
    EXPECT_TRUE(traceSet.addTrace("test_data/ust_b/ust/uid/1000/64-bit"));

    size_t num_events = 0;

    for (const EventValue& event : traceSet) {
        ASSERT_LT(num_events, kExpectedNumEvents);

        std::string eventString;
        EXPECT_TRUE(value::ToString(&event, &eventString));

        EXPECT_STREQ(kExpectedEvents[num_events], eventString.c_str());

        ++num_events;
    }
}

}  // namespace value
}  // namespace tibee
