import os

Import('lib_env')

sources = [
    'CanonizeSequence.cpp',
    'DynamicMatching.cpp',
    'ExecutionBuilder.cpp',
    'FindRepetitions.cpp',
    'Graph.cpp',
    'HierarchyMatcher.cpp',
    'Matcher.cpp',
    'Node.cpp',
    'NodeProperties.cpp',
    'PreorderIterator.cpp',
    'StateTimers.cpp',
]

Return(['sources'])
